use spider_util::constants::{
    BLOOM_BUFFER_FLUSH_SIZE, BLOOM_FILTER_HASH_FUNCTIONS, CONNECT_TIMEOUT_SECS,
    DEFAULT_POOL_MAX_IDLE_PER_HOST, DEFAULT_REQUEST_TIMEOUT_SECS, DEFAULT_VISITED_CACHE_SIZE,
    HOST_SPECIFIC_POOL_MAX_IDLE_PER_HOST, MAX_PENDING_REQUESTS, RATE_LIMIT_INITIAL_DELAY_MS,
    RATE_LIMIT_MAX_DELAY_MS, RATE_LIMIT_MAX_JITTER_MS, RATE_LIMIT_MIN_DELAY_MS,
    SQLITE_CHANNEL_CAPACITY, STREAM_JSON_DEFAULT_BATCH_SIZE, VISITED_URL_CACHE_CAPACITY,
};

#[test]
fn constants_invariants_hold() {
    assert!(DEFAULT_VISITED_CACHE_SIZE <= VISITED_URL_CACHE_CAPACITY);
    assert!(MAX_PENDING_REQUESTS > 0);
    assert!(BLOOM_FILTER_HASH_FUNCTIONS > 0);
    assert!(BLOOM_BUFFER_FLUSH_SIZE > 0);

    assert!(RATE_LIMIT_MIN_DELAY_MS <= RATE_LIMIT_INITIAL_DELAY_MS);
    assert!(RATE_LIMIT_INITIAL_DELAY_MS <= RATE_LIMIT_MAX_DELAY_MS);
    assert!(RATE_LIMIT_MAX_JITTER_MS <= RATE_LIMIT_MAX_DELAY_MS);

    assert!(CONNECT_TIMEOUT_SECS <= DEFAULT_REQUEST_TIMEOUT_SECS);
    assert!(HOST_SPECIFIC_POOL_MAX_IDLE_PER_HOST <= DEFAULT_POOL_MAX_IDLE_PER_HOST);
    assert!(SQLITE_CHANNEL_CAPACITY > 0);
    assert!(STREAM_JSON_DEFAULT_BATCH_SIZE > 0);
}
