[package]
name = "spider-downloader"
version = "1.0.2"
edition = "2024"
description = "Downloader component for the spider-lib web scraping framework"
license = "MIT"
documentation = "https://docs.rs/spider-downloader"
homepage = "https://github.com/mzyui/spider-lib"
repository = "https://github.com/mzyui/spider-lib"
readme = "README.md"

[dependencies]
async-trait.workspace = true
reqwest.workspace = true
spider-util = { version = "0.3.4", path = "../spider-util" }
log.workspace = true
dashmap.workspace = true
moka.workspace = true

[dev-dependencies]
